### ISSUE TITLE
[Feature] Add device name in sensor

### ISSUE THREAD

**Issue by djiesr** [tomaae/homeassistant-truenas#101]
The name of the sensor is too common.
sensor.temperature
sensor.uptime
sensor.memory_usage

But you in real you have 
sensor.temperature_1
sensor.uptime_3
sensor.memory_usage_3

The standard on HA, it's to place the name of the entity before the sensor
sensor.truenas_temperature
sensor.truenas_uptime
sensor.truenas_memory_usage

If you have another server can be that
sensor.truenas_personnal_memory_usage
sensor.truenas_business_memory_usage

It's easiest to found the sensor in the list when you make your dashboard or when you make automation.

**Comment by SteffenViperKoch** [comment]
maybe naming should be something like "sensor.truenas_[NameOfIntegrationEntry]_entity"

**Comment by djiesr** [comment]
When you set "Name of the integration" when you add the device was perfect. I don't think you need add "truenas_" before it. Or if you want, you can name it "truenas_<integration name>".

**Comment by tomaae** [comment]
using just domain name as prefix should do fine. so whatever you name the device in gui.
that should work great for most use cases, maybe with some edge cases.

**Comment by muddro1** [comment]
This seemed to work in 1.2.4, but broke again in 1.2.5

**Comment by tomaae** [comment]
got solution, it will be "<instance name>_<device name (as seen in UI integration page)>_<default entity name>"
Example:
![image](https://github.com/tomaae/homeassistant-truenas/assets/23486452/7034211a-ea97-415e-b25f-32a2da0a4dd5)
note: "Truenas" is how I named the integration instance on my development server
It will be available in next release. Not commited in master yet due to device name inconsistencies I need to fix.
