### ISSUE TITLE
[Bug] after every home-assistant reboot the integration displays an available update for my TrueNAS with version "unknown"

### ISSUE THREAD

**Issue by mindgam3s** [tomaae/homeassistant-truenas#174]
## Describe the issue
after every home-assistant reboot the integration displays an available update for my TrueNAS with version "unknown"
this prompt removes itself after a few seconds right after correcting itself to the real current version being "available"

## How to reproduce the issue
reboot homeassistant
see an available update even though TrueNAS is on the latest version already

## Expected behavior
no update prompt available on boot if not necessary

## Screenshots
![grafik](https://github.com/user-attachments/assets/b4a729cd-76db-4037-9c54-884ab65f5935)
![grafik](https://github.com/user-attachments/assets/6bf67c91-62e2-43d4-9e30-2d00286141d1)

## Software versions
Core 2024.10.1
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.2
------------------------
TrueNAS OS version 13.0-U6.2
------------------------
TrueNAS homeassistant HACS integration version v1.2.5

**Comment by mindgam3s** [comment]
keep-alive

**Comment by itsniawan** [comment]
I think it happen because the default value of `"updated_version"` is `"unknown"`. The current version didn't match the `"updated_version"`, which current value is `"unknown"`, so the system report that there is an update.
The workaround is by making the default value of `"updated_version"` to current local version, this will prevent false report by the system before its get the real latest version from TrueNAS.
The default value is located in [coordinator.py](https://github.com/tomaae/homeassistant-truenas/tree/master/custom_components/truenas/coordinator.py) line 285. 
Change it from `"default": "unknown"` to ```"default": self.ds["system_info"]["version"]```
