### ISSUE TITLE
[Bug] boot-pool is unavailable on TrueNAS Scale

### ISSUE THREAD

**Issue by chadweimer** [tomaae/homeassistant-truenas#60]
## Describe the issue
boot-pool is unavailable on TrueNAS Scale

## How to reproduce the issue
1. Install via HACS
2. Add the integration
3. Note that "boot-pool" entities show as "Unavailable"

## Expected behavior
boot-pool entities should be available similar to other ZFS pools

## Screenshots
![image](https://user-images.githubusercontent.com/1165476/209248832-1ab7ac13-a566-4203-9500-432ccc4570ae.png)

## Software versions

 - Home Assistant version: 2022.12.8
 - TrueNAS integration version: 1.2.3
 - TrueNAS version: scale 22.12.0

## Additional context
This problem existed before the upgrade to 2022.12.0 aka Bluefin. The boot-pool entities were working when using TrueNAS Core, but I have also removed and re-added the integration since migrating from core to scale.

**Comment by tomaae** [comment]
pretty sure it worked fine before.
I will be checking out new scale over holidays, we see if it does same for me,

**Comment by krzysiek2788** [comment]
I ahve the same issue. On TrueNas Scale Anglefish it was working fine on Bluefin not available.

**Comment by tomaae** [comment]
yea, I still need to test everything on bluefin. but since this is only reported issue, it should be fine.

**Comment by krzysiek2788** [comment]
Ok I find out what have changed in Bluefin. According to your code:
![image](https://user-images.githubusercontent.com/61471407/212469372-1f658c18-6c81-4e2c-a20d-f1258161b716.png)
The **Guid** should be in main tree when you execute **boot/get_state**, where in Bluefin they have change location of **Guid** or missed it and it is now in **topology/data**
![image](https://user-images.githubusercontent.com/61471407/212469421-23d5f61f-c07f-4815-8a19-72e3a2150cf2.png)
I tried to do it my self but I'm not so keen on python to figure it out, how it should look like in order to work.
