### ISSUE TITLE
No response from host.[Question]

### ISSUE THREAD

**Issue by Pumpedplop** [tomaae/homeassistant-truenas#88]
Like in the tittle said I always get the error: "No response from host."
I can't find a way to resolve this, could it be because I am running the home assistant inside a truenas scale virtualization? 
I followed this guide for installing HA (" https://community.home-assistant.io/t/installing-haos-in-a-vm-on-truenas-scale/511393 ").

**Comment by tomaae** [comment]
It means you HA installation cant access truenas. Its probably something in your network setup.
I dont have experience with scale VMs, so cant help much there. Try to ping it from HA cli and continue from there.

**Comment by hansolo199532** [comment]
Same issue on my end =(

**Comment by tomaae** [comment]
it is a network issue, not much I can do there.

**Comment by remer** [comment]
I had this issue and fixed it. I have HAOS running in a VM, and I normally access it through a cloudflare tunnel. After I did the following the issues was resolved and I was able to connect the TrueNAS integration:

1.  Follow this guide to create a bridge: https://www.truenas.com/docs/scale/scaletutorials/virtualization/accessingnasfromvm/
Note: I lost access to my local IPs when following the guide (after stopping pihole) and panicked a little. Restarting my router fixed that problem.

2.  Access the HA interface through your local IP, rather than the cloudflare tunnel site.

**Comment by hansolo199532** [comment]
I actually solved it - you need to setup a bridge on truenas and add your primary adapter . Works fine now

Zac  Gaetano
Arri Trinity - Cam Department
- Live Production
4104874441
***@***.***
https://wilddragon.net/

**Comment by Samega7Cattac** [comment]
I'm having the same issue.
But I think that's bc I have TrueNAS on a non-standard port.
Does it support specifying the port to be used in the host field?

**Comment by tomaae** [comment]
just add a port as normal

**Comment by remer** [comment]
> I'm having the same issue.
> But I think that's bc I have TrueNAS on a non-standard port.
> Does it support specifying the port to be used in the host field?

I’m using a non-standard port too and the instructions I posted above worked for me.

**Comment by Samega7Cattac** [comment]
@remer It worked but now I can't connect to apps, but that's another issue
